version: '3'

services:
    app:
        image: triple-triad:latest
        container_name: ttriad-main
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        tty: true